<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<RootNamespace>FishLens_App</RootNamespace>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<ApplicationManifest></ApplicationManifest>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="MailKit" Version="4.16.0" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.81.0" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Themes\Controls\" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Fonts\PlusJakartaSans-Regular.ttf"/>
		<Resource Include="Fonts\PlusJakartaSans-Medium.ttf"/>
		<Resource Include="Fonts\PlusJakartaSans-SemiBold.ttf"/>
		<Resource Include="Fonts\PlusJakartaSans-Bold.ttf"/>
		<Resource Include="Fonts\DMSans-Regular.ttf"/>
		<Resource Include="Fonts\DMSans-Medium.ttf"/>
		<Resource Include="Fonts\DMSans-SemiBold.ttf"/>
	</ItemGroup>
</Project>
